### ISSUE TITLE
Game.cpp: line 402 && 407

### ISSUE THREAD

**Issue by Peter829** [popiop4/Newman_CSCI2270_FinalProject#1]
Hi,

I am having some issues during the initial comiple of your code. Specifically, on line 402
"error: varible 'Game::wait(int)::timespec req' has initializer but incomplete type"
and line 407
"error: 'nanosleep' was not declared in this scope"
I have downloaded your main.cpp, Game.cpp, and Game.h files and then proceeded to compile.

**Comment by popiop4** [comment]
Peter,

The compiler I am using might be a different version, if you comment out
everything in the wait function (lines 402-408) it'll still work just fine.
All it did was make the program wait for a second in-between players turns.

**Comment by Peter829** [comment]
It was exactly that! Just commented the wait function and a few other wait(1000) lines and it works well.
